const decode = require('geojson-polyline').decode;
const polygon = {
  type: 'Polygon',
  coordinates: [
    'ahulJs~p`AE]Y[GUGGOEKAO@UISAWLWRCAG^KYIBCHAvBGlBCNONMZIt@?v@EVKRQLa@Js@?[JO?UCWDq@l@SZUFOPWL_@B]?MCc@QG?EDOZK~@FjBC|@AjCTdBVRVFBD@b@?bBDp@Jr@HvBPzA?LPLR?LQHEVAHDTZr@bBDb@DbBRlAPf@DJB@p@EHDF\\@lAJlBBxAAh@Gt@GXOd@Eb@PtA?\\Gn@WlAO`A[xC@ZNdAJfC?f@EX[lAi@nCOzAUfAMjAK`@MfBW`AEv@Q~@KhA_@jCCf@DxACVFb@^t@v@jCpAtBRl@b@z@RVFTH|AEb@CrAFnCG^OXWPY`@W?OBq@?}@XWPYHy@\\eAh@a@Pu@f@a@PSR[La@VYXm@x@aAfBm@pAwAbEa@|@U^y@~B_AfBa@fAg@dBmArCe@tBQ|ACb@Mb@@J\\bAHp@@VIf@IFGAw@_AkAkAMSUQQGIBIJWp@o@nCIj@_@dBQ^u@vAg@xAa@`CGZIJo@TG?GGKOMYu@gA}@}Ac@m@Sc@Ye@{BwCyAyBg@i@]Wg@Ke@@YLq@p@e@dA_@xAQzAId@?xCBt@Ft@PrA^tEEnAG|@Mv@?XHVN`@H`@`@`BR~@d@fC^bD`@vFTpBHhBUjCGhBHfCArABhAJd@d@hAn@bCn@bBNV`@o@RSTKHCH@RLTf@P`ATv@N\\X`@v@lBJpADPb@p@p@x@P\\n@dAj@~Ap@`AN\\`@tAz@|@d@^H?TYx@mB^o@HG^ETDx@d@fD|CZJRAVDHD`@h@HDVGXe@f@g@NWHEJ@HHh@|@NBBDXl@VVNXl@j@FAH^FJ^\\`@v@XPJJJTPVVr@JPLNTNNT`@\\d@v@XTD@XSTYFEHF\\f@@P_AlCCX@JLZZPVt@NRXPj@Nh@`@x@v@RLJLHPdA`GXpCv@xD`@lAj@tAfApEb@zAlAzBVx@Rx@RhBFfBLpARvCn@lFV|Ad@`B~@dEd@`B^zB`@zCNt@Lf@\\p@ZTRJVDHCDC|@wA`@Wf@Wb@KNBx@`AHFL@^Ql@g@\\KRWJUJ]Jo@B{AEo@S{AOmBEQBgAQ{BUu@c@_Ac@mA[oBIy@e@wBWsBGYSg@eAqA[y@o@}Cq@wDq@iCg@aBu@gCk@sC{@oDEa@?MCBAAC{@Ba@Jg@|@oCD]?k@Hw@?[Q{AgAgGsAyEe@oACa@Ke@o@sBu@cB[e@USm@S[CgABo@FSAiAQw@YQOc@s@Yi@o@{BG[Ee@?eAD{@L}@J_@Z{@d@w@j@w@x@aAf@c@t@kA~@{Bp@{B`@gBN_ALqALgBVcGD_@f@oD^_Bb@uAn@_BlAaC|MeUp@sAn@{ArAqFv@eEZ_CDEJADKRyBBgBLaBD]LuCVuB?OGc@Ak@XiBHcCr@{MLuDFwHA{BIwBMaBk@yD]iA_AiBUq@Ik@@kAHoAKg@UOQk@MoBIyC[_A[qBBcAFAFDDCCC?KD[?OYeAOUg@mAOqAw@wAYkASi@CO?KLUn@u@b@s@b@eAv@aBPe@^cBFm@EuAk@oDqA}D[q@]eAOy@?u@F}@t@_FZuATeBD_ACa@EYKUu@qAy@eAYUWQe@e@Yi@]_@Ue@a@kAUg@MOUOESA_@GGGAWUGi@QSO]k@c@[O]GUO{@y@[a@e@Y]]KWW_@q@c@_@q@Se@@MDIJEJAf@BDCBI?]U{AAe@',
  ],
};
const geoJSON = decode(polygon);
console.log(geoJSON);
